Repository fedora-copr/copr, pull requests merged in 2024-09, with the labels that each got.

#3391 Don't upload RPM packages to Pulp as artifacts
  backend/copr_backend/pulp.py
  backend/copr_backend/storage.py
Labels: pulp

#3382 frontend: add script for changing storage for a project
  frontend/coprs_frontend/commands/change_storage.py
  frontend/coprs_frontend/coprs/logic/actions_logic.py
  frontend/coprs_frontend/manage.py
Labels: pulp

#3403 Add pulp container to our docker-compose
  docker-compose.yaml
  docker/backend/files/home/copr/.config/pulp/cli.toml
Labels: containers, pulp

#3428 Fix traceback caused by None timeout
  frontend/coprs_frontend/coprs/logic/builds_logic.py
Labels: release-blocker

#3430 frontend: add missing dialect ref for identifier_preparer
  frontend/coprs_frontend/coprs/logic/batches_logic.py
Labels: release-blocker

#3431 beaker: update fedora version to f41 for testing
  beaker-tests/DockerTestEnv/Dockerfile
  beaker-tests/Sanity/copr-cli-basic-operations/config
Labels: release-blocker
