Repository fedora-copr/copr, pull requests merged in 2025-10, with the labels that each got.

#3916 frontend, cli: Add wildcard support for 'Packit allowed forge projects'
  cli/copr_cli/main.py
  frontend/coprs_frontend/coprs/logic/coprs_logic.py
  frontend/coprs_frontend/coprs/templates/coprs/_coprs_forms.html
  frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py
  frontend/coprs_frontend/tests/test_logic/test_coprs_logic.py
Labels: pr/failing-ci, pr/missing-review

#3924 Add option to migrate all projects for an owner
  backend/run/copr-change-storage
  frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py
Labels: pulp, pr/failing-ci, pr/missing-review

#3926 doc: upload the golden image howto
  doc/how_to_upgrade_builders.rst
Labels: pr/missing-review

#3928 Fix hitcounter auth to frontend
  backend/copr_backend/hitcounter.py
Labels: pr/missing-review

#3930 testing-farm: skeleton for sanity tests
  .fmf/version
  .packit.yaml
  testing-farm/plans/sanity.fmf
  testing-farm/prepare/machine-prepare.yml
  testing-farm/tests/sanity/main.fmf
  testing-farm/tests/sanity/test.sh
Labels: pr/missing-review

#3934 frontend: do not traceback for OAuthError
  frontend/coprs_frontend/coprs/views/misc.py
Labels: pr/failing-ci, pr/missing-review
