Repository fedora-copr/copr, pull requests merged in 2025-06, with the labels that each got.

#3741 backend: pulp in production and STG uses a bit different URLs
  backend/run/copr-pulp-json-to-labels
Labels: pulp, pr/missing-review

#3742 memory optimalization in copr_log_hitcounter.py
  backend/run/copr_log_hitcounter.py
Labels: pr/missing-review

#3750 Create one repository version and publication per chroot
  backend/copr_backend/background_worker_build.py
  backend/copr_backend/pulp.py
  backend/copr_backend/storage.py
  backend/run/copr-change-storage
Labels: pr/failing-ci, pr/missing-review

#3759 frontend: hide excessive CoprDirs under a details tag
  frontend/coprs_frontend/coprs/static/css/copr-flavor.css
  frontend/coprs_frontend/coprs/templates/coprs/detail/builds.html
  frontend/coprs_frontend/generate_colorscheme
Labels: pr/failing-ci, pr/missing-review

#3762 frontend: disable network when crearing a new fedora review project
  frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
Labels: pr/failing-ci, pr/missing-review

#3755 doc: stop using deprecated get_html_theme_path funciton
  doc/conf.py
Labels: pr/missing-review

#3767 backend: fix ftbfs for deepcopy not able to handle itertools.count
  backend/tests/test_worker_manager.py
Labels: pr/missing-review
