Repository fedora-copr/copr, pull requests merged in 2025-07, with the labels that each got.

#3771 backend: fix false-positive failures for build deletion
  backend/copr_backend/storage.py
Labels: pr/missing-review

#3778 Update documentation for builder images to use image-buidler and bootc
  doc/how_to_upgrade_builders.rst
Labels: pr/missing-review

#3781 backend: drop the 'Z' suffix from timestamp
  backend/run/copr-backend-generate-graphs
Labels: hot-fixed

#3782 backend: Stop using deprecated %py3_build/%py3_install macros
  backend/copr-backend.spec
Labels: pr/missing-review

#3783 backend: fix race condition in BatchedCreaterepo
  backend/copr_backend/createrepo.py
  backend/run/copr-repo
Labels: bug, pr/missing-review

#3787 frontend: Fix AI button visibility
  frontend/coprs_frontend/coprs/filters.py
  frontend/coprs_frontend/coprs/templates/_helpers.html
  frontend/coprs_frontend/coprs/templates/coprs/detail/build.html
Labels: pr/missing-review

#3791 modernize spec file and drop old stuff
  cli/copr-cli.spec
  selinux/copr-selinux.spec
Labels: pr/failing-ci, pr/missing-review

#3790 messaging: Stop using deprecated %py3_build/%py3_install macros
  messaging/copr-messaging.spec
Labels: pr/missing-review

#3788 frontend: drop support for OID auth
  frontend/copr-frontend.spec
  frontend/coprs_frontend/coprs/__init__.py
  frontend/coprs_frontend/coprs/auth.py
  frontend/coprs_frontend/coprs/context_processors.py
  frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_general.py
  frontend/coprs_frontend/coprs/views/misc.py
  frontend/coprs_frontend/tests/coprs_test_case.py
  frontend/coprs_frontend/tests/test_logging.py
  frontend/coprs_frontend/tests/test_views/test_admin/test_admin_general.py
  frontend/coprs_frontend/tests/test_views/test_misc.py
Labels: pr/failing-ci, pr/missing-review

#3801 backend: make sure every PULP api call is logged
  backend/copr_backend/pulp.py
Labels: pulp, pr/missing-review

#3809 pylint: don't use @classmethod + @property
  .pylintpath/pylint_copr_plugin.py
Labels: ci-blocker
