Repository fedora-copr/copr, pull requests merged in 2025-03, with the labels that each got.

#3648 beaker-tests-sanity: remove unnecessary MBS test
  beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh
Labels: pr/missing-review

#3636 frontend: use after/with-build-id fields when "rebuilding all"
  frontend/coprs_frontend/coprs/logic/builds_logic.py
  frontend/coprs_frontend/coprs/logic/packages_logic.py
  frontend/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py
Labels: pr/missing-review

#3608 frontend: provide log-detective explain integration for failed builds
  frontend/coprs_frontend/coprs/templates/_helpers.html
  frontend/coprs_frontend/coprs/templates/coprs/detail/_builds_forms.html
  frontend/coprs_frontend/coprs/templates/coprs/detail/build.html
Labels: pr/missing-review

#3667 unify bindir and sbindir
  backend/copr-backend.spec
  selinux/copr-selinux.spec
Labels: pr/missing-review

#3651 Revert "convert eror message to binary text before emitting"
  frontend/coprs_frontend/coprs/logic/complex_logic.py
Labels: pr/missing-review

#3674 frontend: fix code formatting test causing FTBFS
  frontend/coprs_frontend/tests/test_views/test_coprs_ns/test_coprs_general.py
Labels: release-blocker, pr/missing-review

#3663 Add sysusers.d config file to allow rpm to create users/groups automatically
  frontend/conf/copr-frontend.sysusers.conf
  frontend/copr-frontend.spec
Labels: release-blocker, pr/failing-ci, pr/missing-review

#3673 frontend: fix FTBFS when using python below 3.12
  frontend/coprs_frontend/coprs/helpers.py
  frontend/coprs_frontend/coprs/logic/complex_logic.py
  frontend/coprs_frontend/coprs/mail.py
Labels: release-blocker, pr/failing-ci, pr/missing-review

#3665 Add sysusers.d config file to allow rpm to create users/groups automatically
  keygen/configs/copr-keygen.sysusers.conf
  keygen/copr-keygen.spec
Labels: release-blocker, pr/failing-ci, pr/missing-review

#3676 messaging: fix FTBFS caused by sphinx config
  messaging/docs/conf.py
Labels: release-blocker, pr/missing-review

#3668 Add sysusers.d config file to allow rpm to create users/groups automatically
  backend/conf/copr-backend.sysusers.conf
  backend/copr-backend.spec
Labels: release-blocker, pr/missing-review

#3649 frontend: 404 when build_chroot is not found in database from task_id
  frontend/coprs_frontend/coprs/logic/builds_logic.py
  frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py
Labels: pr/missing-review

#3678 doc: add release notes for copr update
  doc/release-notes/2025-03-26.rst
  doc/release_notes.rst
Labels: pr/missing-review
